### ISSUE TITLE
Add new argument to expose coala quickstart version

### ISSUE THREAD

**Issue by meetmangukiya** [coala/coala-quickstart#180] opened 2017-09-14 13:56 UTC
Currently there is no way to check quickstart version using the quickstart binary itself(or it is not documented in the help). Add a new argument  that prints quickstart version.

**Comment by satwikkansal** [comment] 2017-10-11 20:19
Related to https://github.com/coala/coala-quickstart/issues/147

**Comment by Makman2** [comment] 2017-10-20 13:11
Not only related, this is a duplicate of #147.

**Closed by Makman2** 2017-10-20 13:11 UTC
Labels: difficulty/low
